### ISSUE TITLE
Browser error due to mixed content

### ISSUE THREAD

**Issue by maaaaz** [rs-anantmishra/streamsphere#49] opened 2024-12-06 11:43 UTC
Hello there,

Thank you for your project.
I justed tried it, but stumbled upon different bugs that I will document in different Github "issues".

The first one is this: when exposing the streamsphere front-end with HTTPS, browsers refuse to perform subsequent request as they are using "http" instead of "https". This is called ["mixed content"](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content).

Indeed the first request performed when launching the front-end is `http://<FQDN_or_IP>:<PORT>/api/download/metadata` instead of `https://`

So the whole project is unusable.

Cheers.

**Comment by rs-anantmishra** [comment] 2024-12-06 18:41
Hello,

Streamsphere is a project that is in its infancy, it does not implement https as of right now, if you do try to use it with an https connection, it will error out and mixed content is the error you will get as you have stated above.

If you do wish to use streamsphere at this point in time, it will have to be via http only.

At the moment, there are some things that need an architectural change that need to be implemented before any of this can happen. 

Closing as this is not a bug, it's just not yet implemented! However, thanks for taking out the time to investigate and provide your feedback! I will be creating a story for https once the application design is correctly implemented! :)

Cheers!

**Closed as completed by rs-anantmishra** 2024-12-06 18:41 UTC
Labels: invalid
